
// DEVELOPMENT

### GET /users (Role Customer)
GET http://localhost:8080/users HTTP/1.1
Content-Type: application/json
email: moroni.art.motta@gmail.com
password: 123456789

### GET /users (Role Admin)
GET http://localhost:8080/users HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight

### POST /users
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight

{
  "age": "22",
  "document": "98765432101234",
  "last_name": "Doe",
  "name": "John",
  "password": "dummypassword",
  "role": "admin",
  "email": "example@gmail.com"
}
### PUT /users/66fb4624f0c67c4d63214ae5
PUT http://localhost:8080/users/66fb4624f0c67c4d63214ae5 HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight

{
    
"age": "75"
}

### GET /users/66fb4624f0c67c4d63214ae5 (Using Admin Role)
GET http://localhost:8080/users/66fb4624f0c67c4d63214ae5 HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight

### GET /users/66fb4624f0c67c4d63214ae6 (Using Customer Role)
GET http://localhost:8080/users/66fb4624f0c67c4d63214ae6 HTTP/1.1
Content-Type: application/json
email: moroni.art.motta@gmail.com
password: 123456789

### DELETE /users/66fb4624f0c67c4d63214ae5
DELETE http://localhost:8080/users/66fb4624f0c67c4d63214ae5 HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight



# PRODUCTION
### GET /unknown

GET https://cse341-project1-1-uaff.onrender.com/unknown HTTP/1.1
Content-Type: application/json
email: moroni.art.motta@gmail.com
password: 123456789

### GET /users (Role Customer)
GET https://cse341-project1-1-uaff.onrender.com/users HTTP/1.1
Content-Type: application/json
email: moroni.art.motta@gmail.com
password: 123456789

### GET /users (Role Admin)
GET https://cse341-project1-1-uaff.onrender.com/users HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight

### POST /users
POST https://cse341-project1-1-uaff.onrender.com/users HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight

{
    "age": "22",
    "document": "98765432101234",
    "last_name": "Doe",
    "name": "John",
    "password": "dummypassword",
    "role": "admin",
    "email": "example@gmail.com"
}

### PUT /users/66fb4624f0c67c4d63214ae5
PUT https://cse341-project1-1-uaff.onrender.com/users/66fb4624f0c67c4d63214ae5 HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight

{
    "age": "75"
}

### GET /users/66fb4624f0c67c4d63214ae5 (Using Admin Role)
GET https://cse341-project1-1-uaff.onrender.com/users/66fb4624f0c67c4d63214ae5 HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight

### GET /users/66fb4624f0c67c4d63214ae6 (Using Customer Role)
GET https://cse341-project1-1-uaff.onrender.com/users/66fb4624f0c67c4d63214ae6 HTTP/1.1
Content-Type: application/json
email: moroni.art.motta@gmail.com
password: 123456789

### DELETE /users/66fb4624f0c67c4d63214ae5
DELETE https://cse341-project1-1-uaff.onrender.com/users/66fb4624f0c67c4d63214ae5 HTTP/1.1
Content-Type: application/json
email: joesmith@gmail.com
password: isawapillaroflight