
// DEVELOPMENT
### GET /contacts
GET http://localhost:8080/contacts

### GET /contacts/66e8e4d6b392f5e5af665987
GET http://localhost:8080/contacts/66e8e4d6b392f5e5af665987

### POST /contacts
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "example@gmail.com",
    "favoriteColor": "Black",
    "birthday": "2001-06-21"
}

### PUT /contacts/66e8e4d6b392f5e5af665987
PUT http://localhost:8080/contacts/66e8e4d6b392f5e5af665987 HTTP/1.1
Content-Type: application/json

{
    "favoriteColor": "Red"
}


### DELETE /contacts/66e8e4d6b392f5e5af665987
DELETE http://localhost:8080/contacts/66f33b560896bd569bbdf304

// PRODUCTION
### GET /contacts
GET https://cse341-project1-fhhx.onrender.com/contacts

### GET /contacts/66e8e4d6b392f5e5af665987
GET https://cse341-project1-fhhx.onrender.com/contacts/66e8e4d6b392f5e5af665987

### POST /contacts
POST https://cse341-project1-fhhx.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "example@outlook.com",
    "favoriteColor": "White",
    "birthday": "2001-06-21"
}
